# GOGS AND POSTGRESS USING SECRET!!

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: backend
spec: {}
status: {}

---

apiVersion: v1
data:
  POSTGRES_PASSWORD: YWxleGE=
  POSTGRES_USER: cm9vdA==
  POSTGRES_DB: dW5uYXRp
kind: Secret
metadata:
  creationTimestamp: null
  name: postgresenv
  namespace: backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
      - image: docker.io/postgres
        name: postgres
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
               name: postgresenv       
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
  namespace: backend
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: frontend
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gogs
  name: gogs
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gogs
    spec:
      containers:
      - image: docker.io/gogs/gogs
        name: gogs
        ports:
        - containerPort: 3000
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gogs
  name: gogs
  namespace: frontend
spec:
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 3000
  selector:
    app: gogs
  type: NodePort
status:
  loadBalancer: {}
